name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - name: Build library
        run: npm run build
      - name: Build demo
        run: npm run build:demo
      - name: List build outputs
        run: |
          ls -la
          ls -la demo || true
          ls -la demo/dist-demo || true
          find . -maxdepth 3 -type d -name "dist*" -print
      - name: Upload demo artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo
          path: demo/dist-demo
